; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

;[env:nanoatmega328]
;platform = atmelavr
;board = nanoatmega328
;framework = arduino


; [env:esp8266]
; platform = espressif8266
; board = esp01_1m
; framework = arduino
; monitor_speed = 115200

[env:esp8266]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 115200
monitor_filters = send_on_enter
                  esp8266_exception_decoder
monitor_echo = yes
monitor_dtr = 0
monitor_rts = 0
; lib_deps = ESP Async WebServer
;   ayushsharma82/WebSerial @ ^1.1.0
lib_ldf_mode = deep

; lib_deps = 
;     https://github.com/me-no-dev/ESPAsyncWebServer.git
;     ESPAsyncTCP
; lib_deps =
;     me-no-dev/ESPAsyncTCP @ ^1.2.2

lib_deps =
    ayushsharma82/WebSerial @ ^1.1.0
    me-no-dev/ESPAsyncTCP @ ^1.2.2
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    bblanchon/ArduinoJson @ ^7.0.0
lib_compat_mode = strict